Решите **линейную** систему уравнений:
$$\left\{
    \begin{array}\\
        3x - 2y + 5z = 7, {линейное\ уравнение}\\
        7x + 4y - 8z = 3, {линейное\ уравнение}\\
        5x\ – 3y - 4z = -12, {линейное\ уравнение}
    \end{array}
\right.$$

1. Методом подстановки.

Выражаем в первом уравнении $y$: $2y = 3x + 5z - 7, => y = \frac{1}{2}(3x + 5z - 7)$

Выражаем во втором $z$: $7x + 2(3x + 5z - 7) - 8z = 3, => z = \frac{1}{2}(-13x + 17)$

Подставляем в выражение для $y$ и далее всё в третье: $5x - \frac{3}{2}(3x + \frac{5}{2}(-13x + 17) - 7) - 2(-13x + 17) = -12$

Избавляемся от дробей: $2x + 15*13x - 15*17 + 42 + 104x - 136 + 48 = 0$

Отсюда $301x = 255 +136 - 90, => x = 1\\
z = \frac{-13 + 17}{2} = 2\\
y = \frac{3 + 5*2 - 7}{2} = 3$

$x = 1, y = 3, z = 2$

2. Методом Крамера.

Матрица коэффициентов: $\begin{pmatrix}
3 & -2 & 5\\
7 & 4 & -8\\
5 & -3 & -4
\end{pmatrix}$

Вектор правой части: $\begin{pmatrix}
7 & 3 & -12
\end{pmatrix}$

Определитель матрицы коэффицентов: $\Delta = \begin{vmatrix}
3 & -2 & 5\\
7 & 4 & -8\\
5 & -3 & -4
\end{vmatrix} = 3*4*(-4) + (-2)*(-8)*5 + 5*7*(-3) - 5*4*5 - (-3)*(-8)*3 - (-4)*7*(-2) = -48 + 80 - 105 - 100 - 72 - 56 = -301$

Определитель для $x$: $\Delta = \begin{vmatrix}
7 & -2 & 5\\
3 & 4 & -8\\
-12 & -3 & -4
\end{vmatrix} = 7*4*(-4) + (-2)*(-8)*(-12) + 5*3*(-3) - (-12)*4*5 - (-3)*(-8)*7 - (-4)*3*(-2) = -112 - 192 - 45 + 240 - 168 - 24 = -301$

Определитель для $y$: $\Delta = \begin{vmatrix}
3 & 7 & 5\\
7 & 3 & -8\\
5 & -12 & -4
\end{vmatrix} = 3*3*(-4) + 7*(-8)*5 + 5*7*(-12) - 5*3*5 - (-12)*(-8)*3 - (-4)*7*7 = -36 - 280 - 420 - 75 - 288 + 196 = -903$

Определитель для $z$: $\Delta = \begin{vmatrix}
3 & -2 & 7\\
7 & 4 & 3\\
5 & -3 & -12
\end{vmatrix} = 3*4*(-12) + (-2)*3*5 + 7*7*(-3) - 5*4*7 - (-3)*3*3 - (-12)*7*(-2) = -144 - 30 - 147 - 140 + 27 - 168 = -602$

Соответственно, $x = \frac{-301}{-301} = 1, y = \frac{-903}{-301} = 3, z = \frac{-602}{-301} = 2$

In [34]:
import numpy as np

a = [[3, -2, 5], [7, 4, -8], [5, -3, -4]]
b = [7, 3, -12]
np_a = np.array(a)
np_b = np.array(b)
result = np.linalg.solve(np_a, np_b)
print(f"x = {int(result[0])}, y = {int(result[1])}, z = {int(result[2])}")

x = 1, y = 3, z = 2


In [35]:
det_a = round(np.linalg.det(np_a), 2)
print(det_a)

-301.0


In [36]:
np_a_1 = np_a.copy().T
np_a_1[0] = np_b
np_a_1 = np_a_1.T
print(np_a_1)
np_a_2 = np_a.copy().T
np_a_2[1] = np_b
np_a_2 = np_a_2.T
print(np_a_2)
np_a_3 = np_a.copy().T
np_a_3[2] = np_b
np_a_3 = np_a_3.T
print(np_a_3)

[[  7  -2   5]
 [  3   4  -8]
 [-12  -3  -4]]
[[  3   7   5]
 [  7   3  -8]
 [  5 -12  -4]]
[[  3  -2   7]
 [  7   4   3]
 [  5  -3 -12]]


In [37]:
det_a_1 = round(np.linalg.det(np_a_1), 2)
print(det_a_1)
det_a_2 = round(np.linalg.det(np_a_2), 2)
print(det_a_2)
det_a_3 = round(np.linalg.det(np_a_3), 2)
print(det_a_3)

-301.0
-903.0
-602.0


In [38]:
x = det_a_1 / det_a
y = det_a_2 / det_a
z = det_a_3 / det_a
print(f"x = {int(x)}, y = {int(y)}, z = {int(z)}")

x = 1, y = 3, z = 2
