5.3.
1. Вычислите матрицу, обратную данной:
$$ \begin{vmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{vmatrix} $$

2. Приведите пример матрицы 4х4, ранг которой равен 1.

1. Определитель матрицы равен 60. Построим матрицу алг.дополнений:
$$ \begin{vmatrix}
-48 & 6 & 32\\
6 & -12 & 6\\
12 & 6 & -8
\end{vmatrix} $$

После транспонирования матрицы алг.дополнений и деления на определитель, обратная исходной будет равна:
$$ \begin{vmatrix}
-0.8 & 0.1 & 0.2\\
0.1 & -0.2 & 0.1\\
\frac{8}{15} & 0.1 & -\frac{2}{15}
\end{vmatrix} $$

In [7]:
import numpy as np

a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
b = np.array([[-0.8, 0.1, 0.2], [0.1, -0.2, 0.1], [8 / 15, 0.1, -2 / 15]])
c = np.dot(a, b)
print(c)
a_1 = np.linalg.inv(a)
print(b)
print(a_1)

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00]
 [-8.8817842e-16  0.0000000e+00  1.0000000e+00]]
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


2. Матрица, все элементы которой за исключением одного, будет иметь ранг 1. Также,например, если в матрице есть 2 ненулевых элемента, стоящих рядом в одной строке или столбце, то её ранг будет равен 1.

$$ \begin{vmatrix}
0 & 0 & 5 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{vmatrix},
\begin{vmatrix}
0 & 3 & 0 & 0\\
0 & -2 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
\end{vmatrix},
\begin{vmatrix}
0 & 0 & 0 & 0\\
0 & 8 & 10 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
\end{vmatrix} $$