6. Найдите одно из псевдорешений вырожденной системы:

$$ \begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix} \times X = \begin{pmatrix}
2\\
5\\
11
\end{pmatrix} $$

Попробуйте также отыскать и нормальное псевдорешение.

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])

In [3]:
Q, R = np.linalg.qr(A)
print(f"Q: {Q}\nR: {R}")

Q: [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R: [[ -8.1240384   -9.6011363  -11.07823419]
 [  0.           0.90453403   1.80906807]
 [  0.           0.           0.        ]]


In [5]:
print(np.dot(Q, R)) # получаем исходную матрицу А
print(np.dot(Q.T, Q)) # получаем единичную матрицу

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -1.66533454e-16 -5.55111512e-17]
 [-1.66533454e-16  1.00000000e+00 -2.77555756e-16]
 [-5.55111512e-17 -2.77555756e-16  1.00000000e+00]]


In [6]:
R1 = R[:2, :2] # выделяем R1/R2
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [8]:
B1 = np.dot(Q.T, B)[:2] # подготавливаем правую часть для R1*X1 = transpose(Q)*B
B1

array([-1.21860576e+01,  1.33226763e-15])

In [9]:
X1 = np.linalg.solve(R1, B1) # полагаем X2 равным 0 и решаем R1*X1 = transpose(Q)*B
X1

array([1.50000000e+00, 1.47287728e-15])

In [10]:
X = np.append(X1, 0) # одно из псевдорешений с Х2 = 0
print (X)
np.linalg.norm(X)

[1.50000000e+00 1.47287728e-15 0.00000000e+00]


1.499999999999999

In [11]:
np.linalg.norm(np.dot(A, X) - B) # выводим невязку

1.2247448713915883

In [14]:
np.linalg.lstsq(A, B, rcond=None) # находим нормальное псеводрешение

(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]))

In [15]:
X = np.array([1.25, 0.5, -0.25]) # выводим нормы для данного решения (невязка совпадает с предыдущей)
np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B)

(1.3693063937629153, 1.224744871391589)