4. Вычислите LU-разложение матрицы:

$$ \begin{pmatrix}
1 & 2 & 3\\
2 & 16 & 21\\
4 & 28 & 73
\end{pmatrix} $$

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg

In [9]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(f"P: {P}\nL: {L}\nU: {U}")
print(np.dot(P.T, A) - np.dot(L, U))

P: [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U: [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
L = np.array([[1, 0, 0],
              [0.25, 1, 0],
              [0.5, -0.4, 1]])
U = np.array([[4, 28, 73],
              [0, -5, -15.25],
              [0, 0, -21.6]])
A = np.dot(L, U)
print(f"A: {A}")

A: [[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]


In [11]:
P, L, U = scipy.linalg.lu(A)

print(f"P: {P}\nL: {L}\nU: {U}")
print(np.dot(P.T, A) - np.dot(L, U))

P: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L: [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U: [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
B = np.array([2, 8, 9])
print(f"det(A) = {np.linalg.det(A)}")
np.linalg.solve(A, B)

det(A) = 432.00000000000017


array([ 9.4212963 ,  0.05324074, -0.50925926])