1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
2. Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.

1. При произведении векторов, представленных, как 1xN на Nx1 (строку на столбец), мы получим результат, идентичный операции скалярного произведения двух векторов (сумма произведений покомпонентно). Если же произведение будет осуществляться в случе Nx1 на 1xN, то в результате будет получена матрица размерности NxN произведений каждого компонента первого вектора на компоненты второго, при этом сумма компонент главной диагонали полученной матрицы также даст скалярное произведение векторов.

In [1]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3, 4]])
b = np.array([[5], [6], [7], [8]])
scalar = np.dot(a, b)
matrix = np.dot(b, a)
print(scalar[0, 0])
print(matrix)
print(sum([matrix[i, j] if i == j else 0 for j in range(len(matrix)) for i in range(len(matrix))]))

70
[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]
70


2. Произведение 5 на Е даст нам диагнональную матрицу с числами 5 по главной диагонали. Определитель данной матрицы будет равен $ 5^5 $ - произведение элементов главной диагонали. Матрица алгебраических дополнений будет также диагональной матрицей, по главной диагонали которой будут находиться числа $ 5^4 $ - при нахождении миноров мы будем получать диагональные матрицы, определители которых равны произведению элементов главной диагонали. Транспонирование матрицы алг.дополнений даст нам ту же матрицу (вращение по главной диагонали). Обратная исходной будет являться также диагональной матрицей, по главной диагонали которой будут находиться числа $ \frac{5^4}{5^5} = \frac{1}{5} = 0.2 $.

In [32]:
n = 5
k = 5
a = np.identity(n)
b = k * a
el = 1 / k
c = np.array([[el if i == j else 0 for j in range(n)] for i in range(n)])
print(c)
np.dot(b, c)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.linalg.inv(b)

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])