1. Решите линейную систему:
$$ \begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix} \times X = \begin{pmatrix}
12\\
2\\
1
\end{pmatrix}$$

Найдём определитель матрицы А - он равен 60 (из задачи 5.2), т.е. не равен 0, следовательно мы можем воспользоваться способом: $ X = A^{-1}*B $

Обратная матрица равна (из 5.3):
$$ \begin{pmatrix}
-0.8 & 0.1 & 0.2\\
0.1 & -0.2 & 0.1\\
\frac{8}{15} & 0.1 & -\frac{2}{15}
\end{pmatrix} $$

Найдём произведение обратной матрицы и матрицы B:
$$ \begin{pmatrix}
-0.8*12 & 0.1*2 & 0.2*1\\
0.1*12 & -0.2*2 & 0.1*1\\
\frac{8}{15}*12 & 0.1*2 & -\frac{2}{15}*1
\end{pmatrix} = \begin{pmatrix}
-9.2\\
0.9\\
\frac{97}{15}
\end{pmatrix}$$

In [5]:
import numpy as np

A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
det = np.linalg.det(A)
print(f"determinant = {det}")
if det > 0:
    A_1 = np.linalg.inv(A)
    print(A_1)
    x = np.dot(A_1, B)
    print(x)

determinant = 59.999999999999986
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
[-9.2         0.9         6.46666667]


In [6]:
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])