3. Сколько решений имеет линейная система:
$$ \begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix} \times X = \begin{pmatrix}
12\\
2\\
1
\end{pmatrix}$$

In [31]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
det = np.linalg.det(A)
print(det)

0.0


In [32]:
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 3)

Система несовместная, решений нет

Меняем вектор правой части:

In [34]:
B = np.array([[0, 1, 2]])
C = np.concatenate((A, B.T), axis=1)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 2)

Система стала совместной:

In [35]:
np.linalg.lstsq(A, B[0], rcond=None)

(array([ 0.44444444,  0.11111111, -0.22222222]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]))

In [36]:
np.dot(A, [ 0.44444444,  0.11111111, -0.22222222]) - B

array([[ 2.77555756e-17, -9.99999994e-09, -1.99999999e-08]])